---
- when: inventory_hostname == groups['dbserver'][0]
  block:
  - name: Generate_db_user_password | {{ role_name | basename }}
    tags: Generate_db_user_password
    shell: openssl rand -hex $((20 + RANDOM % 10))
    register: db_user_password

  - name: Create_database_user | {{ role_name | basename }}
    tags: Create_database_user
    shell: >
      docker exec $(docker ps -f name=^/{{ db_host }}. -q | sed -n 1p)
      psql -U postgres -c
      "CREATE USER {{ db_user }} WITH PASSWORD '{{ db_user_password.stdout }}';"

  - name: Create_database | {{ role_name | basename }}
    tags: Create_database
    shell: >
      docker exec $(docker ps -f name=^/{{ db_host }}. -q | sed -n 1p)
      psql -U postgres -c
      "CREATE DATABASE {{ db }} OWNER {{ db_user }};"

- name: Add_database_user_to_pgpool_pool_passwd_file | {{ role_name | basename }}
  tags: Add_database_user_to_pgpool_pool_passwd_file
  when: db_host == "pgstack_pgpool" and inventory_hostname in groups['dbserver']
  shell: >
    docker exec $(docker ps -f name=^/{{ db_host }}. -q | sed -n 1p)
    pg_md5 --md5auth --config-file=/usr/local/etc/pgpool.conf
    --username={{ db_user }} {{ db_user_password.stdout }}
