---
- name: Restart_nginx | {{ role_name | basename }}
  tags: Restart_nginx
  when: inventory_hostname == groups['docker-swarm-manager'][0]
  command: docker service update --force web-stack_nginx

- name: Restart_uwsgi | {{ role_name | basename }}
  tags: Restart_uwsgi
  when: inventory_hostname == groups['docker-swarm-manager'][0]
  command: docker service update --force web-stack_uwsgi

- name: Django_migrate | {{ role_name | basename }}
  tags: Django_migrate
  vars:
    python_manage_command: "migrate"
  include_tasks: "{{ role_path }}/handlers/django-python-manage-command.yml"

- name: Django_collect_static_files | {{ role_name | basename }}
  tags: Django_collect_static_files
  vars:
    python_manage_command: "collectstatic --noinput -v 0"
  include_tasks: "{{ role_path }}/handlers/django-python-manage-command.yml"
