# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.provider "virtualbox" do |v|
    v.linked_clone = true
  end

  config.vm.box = "ubuntu/bionic64"
  config.vm.box_check_update = false
  # to update box: $ vagrant box update --box "ubuntu/xenial64"

  (1..3).each do |i|
    config.vm.define "sandbox-#{i}" do |node|
      node.vm.hostname = "sandbox-#{i}"
      # Configure network with a static ip
      node.vm.network "private_network", ip: "192.168.33.#{i+10}"
    end
  end
end
