---
- name: Setup_a_python_virtual_env_for_ansible
  tags: Setup_a_python_virtual_env_for_ansible
  hosts: all
  vars:
    # Before a python virtualenv is installed for ansible we use the global python
    ansible_python_interpreter: /usr/bin/python3
  tasks:
  - include_role:
      name: ../../roles/machine-setup/ansible-virtualenv

- name: Machine_general_setup
  tags: Machine_general_setup
  hosts: all
  tasks:
  - include_role:
      name: ../../roles/machine-setup/general

- name: Setup_docker_swarm
  tags: Setup_docker_swarm
  hosts: all
  tasks:
  - include_role:
      name: ../../roles/machine-setup/docker-swarm
