---

# the following variables are not meant to be changed, they are
# constructed from other variables to facilitate writing tasks.

project_dir: "{{ apps_dir }}/{{ deployment_env }}/{{ project }}"

db: "{{ deployment_env }}_{{ project }}"
db_user: "{{ db }}"

db_node: "{{
  groups['postgres-cluster-pgmaster'][0] if database_in_postgres_cluster
  else groups['dbserver'][0]
  }}"

db_docker_service:  "{{
  'pgstack_pgmaster' if database_in_postgres_cluster
  else 'web-stack_postgres'
  }}"

# Be minded that using pgpool while still building the project might cause issues
# due to cached database connections. If that happens restart pgpool using command:
# docker service update pgstack_pgpool --force
clients_db_host:  "{{
  'pgstack_pgpool' if database_in_postgres_cluster and deployment_env == 'prod'
  else db_docker_service
  }}"

djangocms_install_command: "djangocms
    --db postgres://{{ db_user }}:\"{{ hostvars[ db_node ]['db_user_password']['stdout'] }}\"@{{ db_docker_service }}:5432/{{ db }}
    --timezone {{ timezone }}
    --permissions {{ permissions }}
    --languages {{ languages }}
    --bootstrap {{ bootstrap }}
    --starting-page {{ starting_page }}
    --django-version {{ django_version }}
    --cms-version {{ cms_version }}
    --pip-options '--cache-dir /opt/pyvenvs/pipcache'
    -p {{ project_dir }} {{ project }}"
